<?php
namespace Minbaby\OpentracingTrift;

use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TProtocolDecorator;
use Thrift\Type\TType;
use Zipkin\Tracer;

class ServerProtocolDecorator extends TProtocolDecorator
{
    protected $name;
    protected $type;
    protected $seqId;
    /**
     * @var \Zipkin\Tracer
     */
    protected $tracer;
    
    
    protected $nextSpan = false;
    
    /**
     * @inheritdoc
     */
    public function __construct(
        TProtocol $protocol,
        $name,
        $type,
        $seqId,
        Tracer $tracer
    ) {
        parent::__construct($protocol);
        $this->name = $name;
        $this->type = $type;
        $this->seqId = $seqId;
        $this->tracer = $tracer;
    }
    
    /**
     * @inheritdoc
     */
    public function readMessageBegin(&$name, &$type, &$seqid)
    {
        return parent::readMessageBegin($this->name, $this->type, $this->seqId);
    }
    
    /**
     * 从java 抄来的，先放这里，然后再说
     * @deprecated
     */
    public function readBinary()
    {
    }
    
    /**
     * @inheritdoc
     */
    public function readFieldBegin(&$name, &$fieldType, &$fieldId)
    {
        if ($fieldId == SpanProtocol::SPAN_FIELD_ID && $fieldType == TType::MAP) {
            $this->nextSpan = true;
        }
        return parent::readFieldBegin($name, $fieldType, $fieldId);
    }
    
    /**
     * @inheritdoc
     */
    public function readFieldEnd()
    {
        if ($this->nextSpan) {
            $this->nextSpan = false;
            $this->buildSpan();
        }
        return parent::readFieldEnd(); // TODO: Change the autogenerated stub
    }
    
    public function readMessageEnd()
    {
        $activeSpan = $this->tracer->newTrace();
        SpanDecorator::decorate($activeSpan, $this->name, $this->type, $this->seqId);
        
        return parent::readMessageEnd();
    }
    
    private function buildSpan()
    {
        $parent = $this->tracer->openScope();
        $activeSpan = $this->tracer->newTrace();
        SpanDecorator::decorate($activeSpan, $this->name, $this->type, $this->seqId);
    }
}
